services:
  - type: web
    name: mocktopus-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "*"
