# Generated by Django 5.2.1 on 2025-06-30 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('product_management', 'Product Management'), ('data_structures_algorithms', 'Data Structures & Algorithms'), ('system_design', 'System Design'), ('behavioral', 'Behavioral'), ('sql', 'SQL'), ('data_science_ml', 'Data Science & ML'), ('frontend', 'Frontend')], max_length=50)),
                ('slot', models.CharField(choices=[('morning', 'Morning (9:00 - 11:00 AM)'), ('afternoon', 'Afternoon (1:00 - 3:00 PM)'), ('evening', 'Evening (5:00 - 7:00 PM)')], max_length=20)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'date', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('interview_type', models.CharField(choices=[('product_management', 'Product Management'), ('data_structures_algorithms', 'Data Structures & Algorithms'), ('system_design', 'System Design'), ('behavioral', 'Behavioral'), ('sql', 'SQL'), ('data_science_ml', 'Data Science & ML'), ('frontend', 'Frontend')], max_length=50)),
                ('date', models.DateField()),
                ('slot', models.CharField(choices=[('morning', 'Morning (9:00 - 11:00 AM)'), ('afternoon', 'Afternoon (1:00 - 3:00 PM)'), ('evening', 'Evening (5:00 - 7:00 PM)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1_feedback', models.JSONField(blank=True, help_text='Feedback from user1 about user2', null=True)),
                ('user2_feedback', models.JSONField(blank=True, help_text='Feedback from user2 about user1', null=True)),
                ('user1_feedback_submitted', models.BooleanField(default=False)),
                ('user2_feedback_submitted', models.BooleanField(default=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user1', 'user2', 'date', 'slot')},
            },
        ),
    ]
