# Generated by Django 5.2.1 on 2025-06-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='user1_feedback',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user1_feedback_submitted',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user2_feedback',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user2_feedback_submitted',
        ),
    ]
