# Generated by Django 5.2.1 on 2025-06-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_prepare_for_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user1_feedback',
            field=models.JSONField(blank=True, help_text='Feedback from user1 about user2', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='user1_feedback_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='user2_feedback',
            field=models.JSONField(blank=True, help_text='Feedback from user2 about user1', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='user2_feedback_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
