# Generated by Django 5.2.1 on 2025-06-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_alter_interview_status_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='both_users_joined_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when both users joined', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='user1_joined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='user2_joined',
            field=models.BooleanField(default=False),
        ),
    ]
