# Generated by Django 5.2.1 on 2025-06-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_match_both_users_joined_at_match_user1_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_interviewer',
            field=models.CharField(default='user1', help_text='Current interviewer (user1 or user2)', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='current_question',
            field=models.JSONField(blank=True, help_text='Current question being worked on in this room', null=True),
        ),
    ]
