# Generated by Django 5.2.1 on 2025-06-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_match_current_interviewer_match_current_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='code_language',
            field=models.CharField(default='javascript', help_text='Programming language for shared code', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='last_code_update',
            field=models.DateTimeField(blank=True, help_text='Last time code was updated', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='shared_code',
            field=models.TextField(blank=True, default='', help_text='Shared code between both users'),
        ),
    ]
