# Generated by Django 5.2.1 on 2025-06-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_match_code_language_match_last_code_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_round_start',
            field=models.DateTimeField(blank=True, help_text='When current round started', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='interview_start_time',
            field=models.DateTimeField(blank=True, help_text='When the interview timer started', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='round_duration_minutes',
            field=models.IntegerField(default=60, help_text='Duration of each round in minutes'),
        ),
    ]
