# Generated by Django 5.2.3 on 2025-06-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_match_current_round_start_match_interview_start_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interview',
            unique_together=set(),
        ),
    ]
