# Generated by Django 5.2.1 on 2025-06-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='constraints',
            field=models.TextField(blank=True, help_text='Problem constraints'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='examples',
            field=models.JSONField(default=list, help_text='List of example inputs and outputs'),
        ),
        migrations.AddField(
            model_name='question',
            name='hints',
            field=models.TextField(blank=True, help_text='Hints for solving the problem'),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='Untitled QuestionUntitled Question', max_length=200),
            preserve_default=False,
        ),
    ]
